"""Form data extracted from YOKATLAS önlisans (associate degree) search interface."""

# Universities for önlisans programs (note: different list than lisans)
ONLISANS_UNIVERSITIES = [
    "ACIBADEM MEHMET ALİ AYDINLAR ÜNİVERSİTESİ",
    "ADANA ALPARSLAN TÜRKEŞ BİLİM VE TEKNOLOJİ ÜNİVERSİTESİ",
    "ADIYAMAN ÜNİVERSİTESİ",
    "AFYON KOCATEPE ÜNİVERSİTESİ",
    "AFYONKARAHİSAR SAĞLIK BİLİMLERİ ÜNİVERSİTESİ",
    "AĞRI İBRAHİM ÇEÇEN ÜNİVERSİTESİ",
    "AKDENİZ KARPAZ ÜNİVERSİTESİ",
    "AKDENİZ ÜNİVERSİTESİ",
    "AKSARAY ÜNİVERSİTESİ",
    "ALANYA ALAADDİN KEYKUBAT ÜNİVERSİTESİ",
    "ALANYA ÜNİVERSİTESİ",
    "ALTINBAŞ ÜNİVERSİTESİ",
    "AMASYA ÜNİVERSİTESİ",
    "ANADOLU ÜNİVERSİTESİ",
    "ANKARA BİLİM ÜNİVERSİTESİ",
    "ANKARA HACI BAYRAM VELİ ÜNİVERSİTESİ",
    "ANKARA MEDİPOL ÜNİVERSİTESİ",
    "ANKARA MÜZİK VE GÜZEL SANATLAR ÜNİVERSİTESİ",
    "ANKARA ÜNİVERSİTESİ",
    "ANKARA YILDIRIM BEYAZIT ÜNİVERSİTESİ",
    "ANTALYA BELEK ÜNİVERSİTESİ",
    "ANTALYA BİLİM ÜNİVERSİTESİ",
    "ARDAHAN ÜNİVERSİTESİ",
    "ARTVİN ÇORUH ÜNİVERSİTESİ",
    "ATAŞEHİR ADIGÜZEL MESLEK YÜKSEKOKULU",
    "ATATÜRK ÜNİVERSİTESİ",
    "ATILIM ÜNİVERSİTESİ",
    "AVRASYA ÜNİVERSİTESİ",
    "AYDIN ADNAN MENDERES ÜNİVERSİTESİ",
    "BAHÇEŞEHİR ÜNİVERSİTESİ",
    "BALIKESİR ÜNİVERSİTESİ",
    "BANDIRMA ONYEDİ EYLÜL ÜNİVERSİTESİ",
    "BARTIN ÜNİVERSİTESİ",
    "BAŞKENT ÜNİVERSİTESİ",
    "BATMAN ÜNİVERSİTESİ",
    "BAYBURT ÜNİVERSİTESİ",
    "BEYKOZ ÜNİVERSİTESİ",
    "BEZM-İ ÂLEM VAKIF ÜNİVERSİTESİ",
    "BİLECİK ŞEYH EDEBALİ ÜNİVERSİTESİ",
    "BİNGÖL ÜNİVERSİTESİ",
    "BİRUNİ ÜNİVERSİTESİ",
    "BİTLİS EREN ÜNİVERSİTESİ",
    "BOLU ABANT İZZET BAYSAL ÜNİVERSİTESİ",
    "BURDUR MEHMET AKİF ERSOY ÜNİVERSİTESİ",
    "BURSA ULUDAĞ ÜNİVERSİTESİ",
    "ÇAĞ ÜNİVERSİTESİ",
    "ÇANAKKALE ONSEKİZ MART ÜNİVERSİTESİ",
    "ÇANKAYA ÜNİVERSİTESİ",
    "ÇANKIRI KARATEKİN ÜNİVERSİTESİ",
    "ÇUKUROVA ÜNİVERSİTESİ",
    "DEMİROĞLU BİLİM ÜNİVERSİTESİ",
    "DİCLE ÜNİVERSİTESİ",
    "DOĞU AKDENİZ ÜNİVERSİTESİ",
    "DOĞUŞ ÜNİVERSİTESİ",
    "DOKUZ EYLÜL ÜNİVERSİTESİ",
    "DÜZCE ÜNİVERSİTESİ",
    "EGE ÜNİVERSİTESİ",
    "ERCİYES ÜNİVERSİTESİ",
    "ERZİNCAN BİNALİ YILDIRIM ÜNİVERSİTESİ",
    "ESKİŞEHİR OSMANGAZİ ÜNİVERSİTESİ",
    "ESKİŞEHİR TEKNİK ÜNİVERSİTESİ",
    "FATİH SULTAN MEHMET VAKIF ÜNİVERSİTESİ",
    "FENERBAHÇE ÜNİVERSİTESİ",
    "FIRAT ÜNİVERSİTESİ",
    "GALATASARAY ÜNİVERSİTESİ",
    "GAZİ ÜNİVERSİTESİ",
    "GAZİANTEP İSLAM BİLİM VE TEKNOLOJİ ÜNİVERSİTESİ",
    "GAZİANTEP ÜNİVERSİTESİ",
    "GEBZE TEKNİK ÜNİVERSİTESİ",
    "GİRESUN ÜNİVERSİTESİ",
    "GİRNE AMERİKAN ÜNİVERSİTESİ",
    "GİRNE ÜNİVERSİTESİ",
    "GÜMÜŞHANE ÜNİVERSİTESİ",
    "HACETTEPE ÜNİVERSİTESİ",
    "HAKKARİ ÜNİVERSİTESİ",
    "HALİÇ ÜNİVERSİTESİ",
    "HARRAN ÜNİVERSİTESİ",
    "HASAN KALYONCU ÜNİVERSİTESİ",
    "HATAY MUSTAFA KEMAL ÜNİVERSİTESİ",
    "HİTİT ÜNİVERSİTESİ",
    "HOCA AHMET YESEVİ ULUSLARARASI TÜRK-KAZAK ÜNİVERSİTESİ",
    "IĞDIR ÜNİVERSİTESİ",
    "ISPARTA UYGULAMALI BİLİMLER ÜNİVERSİTESİ",
    "IŞIK ÜNİVERSİTESİ",
    "İNÖNÜ ÜNİVERSİTESİ",
    "İSKENDERUN TEKNİK ÜNİVERSİTESİ",
    "İSTANBUL AREL ÜNİVERSİTESİ",
    "İSTANBUL ATLAS ÜNİVERSİTESİ",
    "İSTANBUL AYDIN ÜNİVERSİTESİ",
    "İSTANBUL BEYKENT ÜNİVERSİTESİ",
    "İSTANBUL BİLGİ ÜNİVERSİTESİ",
    "İSTANBUL ESENYURT ÜNİVERSİTESİ",
    "İSTANBUL GALATA ÜNİVERSİTESİ",
    "İSTANBUL GEDİK ÜNİVERSİTESİ",
    "İSTANBUL GELİŞİM ÜNİVERSİTESİ",
    "İSTANBUL KENT ÜNİVERSİTESİ",
    "İSTANBUL KÜLTÜR ÜNİVERSİTESİ",
    "İSTANBUL MEDİPOL ÜNİVERSİTESİ",
    "İSTANBUL NİŞANTAŞI ÜNİVERSİTESİ",
    "İSTANBUL OKAN ÜNİVERSİTESİ",
    "İSTANBUL RUMELİ ÜNİVERSİTESİ",
    "İSTANBUL SAĞLIK VE SOSYAL BİLİMLER MESLEK YÜKSEKOKULU",
    "İSTANBUL SAĞLIK VE TEKNOLOJİ ÜNİVERSİTESİ",
    "İSTANBUL ŞİŞLİ MESLEK YÜKSEKOKULU",
    "İSTANBUL TEKNİK ÜNİVERSİTESİ",
    "İSTANBUL TİCARET ÜNİVERSİTESİ",
    "İSTANBUL TOPKAPI ÜNİVERSİTESİ",
    "İSTANBUL ÜNİVERSİTESİ",
    "İSTANBUL ÜNİVERSİTESİ-CERRAHPAŞA",
    "İSTANBUL YENİ YÜZYIL ÜNİVERSİTESİ",
    "İSTİNYE ÜNİVERSİTESİ",
    "İZMİR BAKIRÇAY ÜNİVERSİTESİ",
    "İZMİR DEMOKRASİ ÜNİVERSİTESİ",
    "İZMİR EKONOMİ ÜNİVERSİTESİ",
    "İZMİR KATİP ÇELEBİ ÜNİVERSİTESİ",
    "İZMİR KAVRAM MESLEK YÜKSEKOKULU",
    "İZMİR TINAZTEPE ÜNİVERSİTESİ",
    "KAFKAS ÜNİVERSİTESİ",
    "KAHRAMANMARAŞ İSTİKLAL ÜNİVERSİTESİ",
    "KAHRAMANMARAŞ SÜTÇÜ İMAM ÜNİVERSİTESİ",
    "KAPADOKYA ÜNİVERSİTESİ",
    "KARABÜK ÜNİVERSİTESİ",
    "KARADENİZ TEKNİK ÜNİVERSİTESİ",
    "KARAMANOĞLU MEHMETBEY ÜNİVERSİTESİ",
    "KASTAMONU ÜNİVERSİTESİ",
    "KAYSERİ ÜNİVERSİTESİ",
    "KIBRIS AMERİKAN ÜNİVERSİTESİ",
    "KIBRIS İLİM ÜNİVERSİTESİ",
    "KIBRIS SAĞLIK VE TOPLUM BİLİMLERİ ÜNİVERSİTESİ",
    "KIRIKKALE ÜNİVERSİTESİ",
    "KIRKLARELİ ÜNİVERSİTESİ",
    "KIRŞEHİR AHİ EVRAN ÜNİVERSİTESİ",
    "KİLİS 7 ARALIK ÜNİVERSİTESİ",
    "KOCAELİ SAĞLIK VE TEKNOLOJİ ÜNİVERSİTESİ",
    "KOCAELİ ÜNİVERSİTESİ",
    "KONYA TEKNİK ÜNİVERSİTESİ",
    "KTO KARATAY ÜNİVERSİTESİ",
    "KÜTAHYA DUMLUPINAR ÜNİVERSİTESİ",
    "KÜTAHYA SAĞLIK BİLİMLERİ ÜNİVERSİTESİ",
    "LEFKE AVRUPA ÜNİVERSİTESİ",
    "LOKMAN HEKİM ÜNİVERSİTESİ",
    "MALATYA TURGUT ÖZAL ÜNİVERSİTESİ",
    "MALTEPE ÜNİVERSİTESİ",
    "MANİSA CELÂL BAYAR ÜNİVERSİTESİ",
    "MARDİN ARTUKLU ÜNİVERSİTESİ",
    "MARMARA ÜNİVERSİTESİ",
    "MERSİN ÜNİVERSİTESİ",
    "MİMAR SİNAN GÜZEL SANATLAR ÜNİVERSİTESİ",
    "MUDANYA ÜNİVERSİTESİ",
    "MUĞLA SITKI KOÇMAN ÜNİVERSİTESİ",
    "MUNZUR ÜNİVERSİTESİ",
    "MUŞ ALPARSLAN ÜNİVERSİTESİ",
    "NECMETTİN ERBAKAN ÜNİVERSİTESİ",
    "NEVŞEHİR HACI BEKTAŞ VELİ ÜNİVERSİTESİ",
    "NİĞDE ÖMER HALİSDEMİR ÜNİVERSİTESİ",
    "NUH NACİ YAZGAN ÜNİVERSİTESİ",
    "ONDOKUZ MAYIS ÜNİVERSİTESİ",
    "ORDU ÜNİVERSİTESİ",
    "OSMANİYE KORKUT ATA ÜNİVERSİTESİ",
    "OSTİM TEKNİK ÜNİVERSİTESİ",
    "PAMUKKALE ÜNİVERSİTESİ",
    "PİRİ REİS ÜNİVERSİTESİ",
    "RECEP TAYYİP ERDOĞAN ÜNİVERSİTESİ",
    "SAĞLIK BİLİMLERİ ÜNİVERSİTESİ",
    "SAKARYA UYGULAMALI BİLİMLER ÜNİVERSİTESİ",
    "SAKARYA ÜNİVERSİTESİ",
    "SAMSUN ÜNİVERSİTESİ",
    "SANKO ÜNİVERSİTESİ",
    "SELÇUK ÜNİVERSİTESİ",
    "SİİRT ÜNİVERSİTESİ",
    "SİNOP ÜNİVERSİTESİ",
    "SİVAS BİLİM VE TEKNOLOJİ ÜNİVERSİTESİ ",
    "SİVAS CUMHURİYET ÜNİVERSİTESİ",
    "SÜLEYMAN DEMİREL ÜNİVERSİTESİ",
    "ŞIRNAK ÜNİVERSİTESİ",
    "TARSUS ÜNİVERSİTESİ",
    "TEKİRDAĞ NAMIK KEMAL ÜNİVERSİTESİ",
    "TOKAT GAZİOSMANPAŞA ÜNİVERSİTESİ",
    "TOROS ÜNİVERSİTESİ",
    "TRABZON ÜNİVERSİTESİ",
    "TRAKYA ÜNİVERSİTESİ",
    "TÜRK HAVA KURUMU ÜNİVERSİTESİ",
    "UFUK ÜNİVERSİTESİ",
    "ULUSLARARASI FİNAL ÜNİVERSİTESİ",
    "ULUSLARARASI KIBRIS ÜNİVERSİTESİ",
    "UŞAK ÜNİVERSİTESİ",
    "ÜSKÜDAR ÜNİVERSİTESİ",
    "VAN YÜZÜNCÜ YIL ÜNİVERSİTESİ",
    "YAKIN DOĞU ÜNİVERSİTESİ",
    "YALOVA ÜNİVERSİTESİ",
    "YAŞAR ÜNİVERSİTESİ",
    "YEDİTEPE ÜNİVERSİTESİ",
    "YOZGAT BOZOK ÜNİVERSİTESİ",
    "YÜKSEK İHTİSAS ÜNİVERSİTESİ",
    "ZONGULDAK BÜLENT ECEVİT ÜNİVERSİTESİ"
]

# Programs for önlisans (associate degree programs)
ONLISANS_PROGRAMS = [
    "Acil Durum ve Afet Yönetimi",
    "Acil Durum ve Afet Yönetimi (Açıköğretim)",
    "Açık Deniz Sondaj Teknolojisi",
    "Açık Deniz Tabanı Uygulamaları Teknolojisi",
    "Ağız ve Diş Sağlığı",
    "Alternatif Enerji Kaynakları Teknolojisi",
    "Ambalaj Tasarımı",
    "Ameliyathane Hizmetleri",
    "Anestezi",
    "Arıcılık",
    "Arka-Yüz Yazılım Geliştirme",
    "Aşçılık",
    "Aşçılık (Açıköğretim)",
    "Atçılık ve Antrenörlüğü",
    "Atık Yönetimi",
    "Avcılık ve Yaban Hayatı",
    "Ayakkabı Tasarım ve Üretimi",
    "Bağcılık",
    "Bağcılık ve Bağ Ürünleri Teknolojisi",
    "Bahçe Tarımı",
    "Bankacılık ve Sigortacılık",
    "Bankacılık ve Sigortacılık (Açıköğretim)",
    "Basım ve Yayım Teknolojileri",
    "Bıçakçılık ve El Aletleri Üretim Teknolojisi",
    "Bilgi Yönetimi",
    "Bilgi Yönetimi (Açıköğretim)",
    "Bilgisayar Destekli Tasarım ve Animasyon",
    "Bilgisayar Operatörlüğü",
    "Bilgisayar Programcılığı",
    "Bilgisayar Programcılığı (Açıköğretim)",
    "Bilgisayar Teknolojisi",
    "Bilişim Güvenliği Teknolojisi",
    "Bitki Koruma",
    "Biyokimya",
    "Biyomedikal Cihaz Teknolojisi",
    "Boya Teknolojisi",
    "Bulut Bilişim Operatörlüğü",
    "Büro Yönetimi ve Yönetici Asistanlığı",
    "Büro Yönetimi ve Yönetici Asistanlığı (Açıköğretim)",
    "Büyük Veri Analistliği",
    "Ceza İnfaz ve Güvenlik Hizmetleri",
    "CNC Programlama ve Operatörlüğü",
    "Coğrafi Bilgi Sistemleri",
    "Coğrafi Bilgi Sistemleri (Açıköğretim)",
    "Çağrı Merkezi Hizmetleri",
    "Çağrı Merkezi Hizmetleri (Açıköğretim)",
    "Çay Tarımı ve İşleme Teknolojisi",
    "Çevre Koruma ve Kontrol",
    "Çevre Sağlığı",
    "Çevre Temizliği ve Denetimi",
    "Çim Alan Tesisi ve Yönetimi",
    "Çini Sanatı ve Tasarımı",
    "Çocuk Gelişimi",
    "Çocuk Gelişimi (Açıköğretim)",
    "Çocuk Koruma ve Bakım Hizmetleri",
    "Çok Boyutlu Modelleme ve Animasyon",
    "Deniz Brokerliği",
    "Deniz Ulaştırma ve İşletme",
    "Deniz ve Liman İşletmeciliği",
    "Deri Teknolojisi",
    "Dezenfeksiyon, Sterilizasyon ve Antisepsi Teknikerliği",
    "Dış Ticaret",
    "Dış Ticaret (Açıköğretim)",
    "Dijital Dönüşüm Elektroniği",
    "Dijital Fabrika Teknolojileri",
    "Diş Protez Teknolojisi",
    "Diyaliz",
    "Doğal Yapı Taşları Teknolojisi",
    "Doğalgaz ve Tesisatı Teknolojisi",
    "Döküm",
    "E-Ticaret ve Pazarlama",
    "E-Ticaret ve Pazarlama (Açıköğretim)",
    "Eczane Hizmetleri",
    "Elektrik",
    "Elektrik Enerjisi Üretim, İletim ve Dağıtımı",
    "Elektrik Enerjisi Üretim, İletim ve Dağıtımı (Açıköğretim)",
    "Elektrikli Cihaz Teknolojisi",
    "Elektronik Haberleşme Teknolojisi",
    "Elektronik Teknolojisi",
    "Elektronörofizyoloji",
    "Emlak Yönetimi",
    "Emlak Yönetimi (Açıköğretim)",
    "Endüstri Ürünleri Tasarımı",
    "Endüstriyel Cam ve Seramik",
    "Endüstriyel Hammaddeler İşleme Teknolojisi",
    "Endüstriyel Kalıpçılık",
    "Enerji Tesisleri İşletmeciliği",
    "Engelli Bakımı ve Rehabilitasyon",
    "Engelli Bakımı ve Rehabilitasyon (Açıköğretim)",
    "Engelliler İçin Gölge Öğreticilik",
    "Eser Koruma",
    "Et ve Ürünleri Teknolojisi",
    "Ev İdaresi (Açıköğretim)",
    "Evde Hasta Bakımı",
    "Fındık Eksperliği",
    "Fidan Yetiştiriciliği",
    "Fizyoterapi",
    "Fotoğrafçılık ve Kameramanlık",
    "Fotoğrafçılık ve Kameramanlık (Açıköğretim)",
    "Geleneksel El Sanatları",
    "Geleneksel Tekstillerin Korunması ve Restorasyonu",
    "Gemi İnşaatı",
    "Gemi Makineleri İşletmeciliği",
    "Geoteknik",
    "Gıda Kalite Kontrolü ve Analizi",
    "Gıda Teknolojisi",
    "Giyim Üretim Teknolojisi",
    "Görsel İletişim",
    "Grafik Tasarımı",
    "Grafik Tasarımı (Açıköğretim)",
    "Halıcılık ve Kilimcilik",
    "Halkla İlişkiler ve Tanıtım",
    "Halkla İlişkiler ve Tanıtım (Açıköğretim)",
    "Harita ve Kadastro",
    "Hasta Bakımı",
    "Hava Aracı İmalat Teknolojileri",
    "Hava Lojistiği",
    "Hibrid ve Elektrikli Taşıtlar Teknolojisi",
    "İç Mekan Tasarımı",
    "İklimlendirme ve Soğutma Teknolojisi",
    "İkram Hizmetleri",
    "İlahiyat (Açıköğretim)",
    "İlk ve Acil Yardım",
    "İmalat Yürütme Sistemleri Operatörlüğü",
    "İnsan Kaynakları Yönetimi",
    "İnsan Kaynakları Yönetimi (Açıköğretim)",
    "İnsansız Araç Teknikerliği",
    "İnsansız Hava Aracı Teknolojisi ve Operatörlüğü",
    "İnşaat Teknolojisi",
    "İnternet ve Ağ Teknolojileri",
    "İslami İlimler (Açıköğretim)",
    "İş Makineleri Operatörlüğü",
    "İş Sağlığı ve Güvenliği",
    "İş Sağlığı ve Güvenliği (Açıköğretim)",
    "İş ve Uğraşı Terapisi",
    "İşletme Yönetimi",
    "İşletme Yönetimi (Açıköğretim)",
    "Kaynak Teknolojisi",
    "Kenevir Dokumacılığı",
    "Kimya Teknolojisi",
    "Kontrol ve Otomasyon Teknolojisi",
    "Kooperatifçilik",
    "Kozmetik Teknolojisi",
    "Kurumsal Bilişim Uzmanlığı",
    "Kuyumculuk ve Takı Tasarımı",
    "Kültürel Miras ve Turizm",
    "Kültürel Miras ve Turizm (Açıköğretim)",
    "Kümes Hayvanları Yetiştiriciliği",
    "Laborant ve Veteriner Sağlık",
    "Laborant ve Veteriner Sağlık (Açıköğretim)",
    "Laboratuvar Teknolojisi",
    "Lojistik",
    "Lojistik (Açıköğretim)",
    "Madencilik Teknolojisi",
    "Mahkeme Büro Hizmetleri",
    "Makine",
    "Makine Resim ve Konstrüksiyonu",
    "Maliye",
    "Mantarcılık",
    "Marina ve Yat İşletmeciliği",
    "Marka İletişimi (Açıköğretim)",
    "Medya ve İletişim",
    "Medya ve İletişim (Açıköğretim)",
    "Mekatronik",
    "Menkul Kıymetler ve Sermaye Piyasası",
    "Menkul Kıymetler ve Sermaye Piyasası (Açıköğretim)",
    "Mermer Teknolojisi",
    "Metalurji",
    "Meyve ve Sebze İşleme Teknolojisi",
    "Mimari Dekoratif Sanatlar",
    "Mimari Restorasyon",
    "Mobil Teknolojileri",
    "Mobilya ve Dekorasyon",
    "Moda Tasarımı",
    "Moda Yönetimi",
    "Muhasebe ve Vergi Uygulamaları",
    "Muhasebe ve Vergi Uygulamaları (Açıköğretim)",
    "Nüfus ve Vatandaşlık",
    "Nükleer Teknoloji ve Radyasyon Güvenliği",
    "Nükleer Tıp Teknikleri",
    "Odyometri",
    "Optisyenlik",
    "Organik Tarım",
    "Ormancılık ve Orman Ürünleri",
    "Ortopedik Protez ve Ortez",
    "Otobüs Kaptanlığı",
    "Otomotiv Gövde ve Yüzey İşlem Teknolojileri",
    "Otomotiv Teknolojisi",
    "Otonom Sistemler Teknikerliği",
    "Otopsi Yardımcılığı",
    "Oyun Geliştirme ve Programlama",
    "Ön-Yüz Yazılım Geliştirme",
    "Özel Güvenlik ve Koruma",
    "Pastacılık ve Ekmekçilik",
    "Patoloji Laboratuvar Teknikleri",
    "Pazarlama",
    "Perakende Satış ve Mağaza Yönetimi",
    "Perakende Satış ve Mağaza Yönetimi (Açıköğretim)",
    "Peyzaj ve Süs Bitkileri Yetiştiriciliği",
    "Podoloji",
    "Polimer Teknolojisi",
    "Posta Hizmetleri",
    "Radyo ve Televizyon Programcılığı",
    "Radyo ve Televizyon Programcılığı (Açıköğretim)",
    "Radyo ve Televizyon Teknolojisi",
    "Radyoterapi",
    "Rafineri ve Petro-Kimya Teknolojisi",
    "Raylı Sistemler Elektrik ve Elektronik",
    "Raylı Sistemler İşletmeciliği",
    "Raylı Sistemler Makine Teknolojisi",
    "Raylı Sistemler Makinistliği",
    "Raylı Sistemler Yol Teknolojisi",
    "Reklamcılık",
    "Reklamcılık (Açıköğretim)",
    "Robotik ve Yapay Zekâ",
    "Saç Bakımı ve Güzellik Hizmetleri",
    "Sağlık Bilgi Sistemleri Teknikerliği",
    "Sağlık Kurumları İşletmeciliği",
    "Sağlık Kurumları İşletmeciliği (Açıköğretim)",
    "Sağlık Turizmi İşletmeciliği",
    "Sahne Işık ve Ses Teknolojileri",
    "Sahne ve Dekor Tasarımı",
    "Sanal ve Artırılmış Gerçeklik",
    "Seracılık",
    "Seramik ve Cam Tasarımı",
    "Siber Güvenlik",
    "Siber Güvenlik Analistliği ve Operatörlüğü",
    "Silah Sanayi Teknikerliği",
    "Sivil Hava Ulaştırma İşletmeciliği",
    "Sivil Hava Ulaştırma İşletmeciliği (Açıköğretim)",
    "Sivil Havacılık Kabin Hizmetleri",
    "Sivil Savunma ve İtfaiyecilik",
    "Sondaj Teknolojisi",
    "Sosyal Güvenlik",
    "Sosyal Hizmetler",
    "Sosyal Hizmetler (Açıköğretim)",
    "Sosyal Medya Yöneticiliği (Açıköğretim)",
    "Spor Yönetimi",
    "Spor Yönetimi (Açıköğretim)",
    "Su Altı Kaynak Teknolojisi",
    "Su Altı Teknolojisi",
    "Su Ürünleri İşleme Teknolojisi",
    "Sulama Teknolojisi",
    "Süt ve Besi Hayvancılığı",
    "Süt ve Ürünleri Teknolojisi",
    "Şarap Üretim Teknolojisi",
    "Tahribatsız Muayene",
    "Tapu ve Kadastro",
    "Tarım Makineleri",
    "Tarım Teknolojisi (Açıköğretim)",
    "Tarımsal İşletmecilik",
    "Tarla Bitkileri",
    "Tekstil Teknolojisi",
    "Tekstil ve Halı Makineleri",
    "Tıbbi Dokümantasyon ve Sekreterlik",
    "Tıbbi Dokümantasyon ve Sekreterlik (Açıköğretim)",
    "Tıbbi Görüntüleme Teknikleri",
    "Tıbbi Laboratuvar Teknikleri",
    "Tıbbi Tanıtım ve Pazarlama",
    "Tıbbi ve Aromatik Bitkiler",
    "Tohumculuk Teknolojisi",
    "Turist Rehberliği",
    "Turizm Animasyonu",
    "Turizm ve Otel İşletmeciliği",
    "Turizm ve Otel İşletmeciliği (Açıköğretim)",
    "Turizm ve Seyahat Hizmetleri",
    "Uçak Teknolojisi",
    "Uçuş Harekat Yöneticiliği",
    "Ulaştırma ve Trafik Hizmetleri",
    "Un ve Unlu Mamuller Teknolojisi",
    "Uygulamalı İngilizce Çevirmenlik",
    "Uygulamalı İspanyolca Çevirmenlik",
    "Üretimde Kalite Kontrol",
    "Web Tasarımı ve Kodlama",
    "Web Tasarımı ve Kodlama (Açıköğretim)",
    "Yağ Endüstrisi",
    "Yapay Zekâ Operatörlüğü",
    "Yapı Denetimi",
    "Yapı Ressamlığı",
    "Yapı Tesisat Teknolojisi",
    "Yapı Yalıtım Teknolojisi",
    "Yaşlı Bakımı",
    "Yaşlı Bakımı (Açıköğretim)",
    "Yat Kaptanlığı",
    "Yeni Medya ve Gazetecilik (Açıköğretim)",
    "Yerel Yönetimler",
    "Yerel Yönetimler (Açıköğretim)",
    "Zeytincilik ve Zeytin İşleme Teknolojisi"
]

# Cities (same as lisans)
ONLISANS_CITIES = [
    "ADANA",
    "ADIYAMAN",
    "AFYONKARAHİSAR",
    "AĞRI",
    "AKSARAY",
    "AMASYA",
    "ANKARA",
    "ANTALYA",
    "ARDAHAN",
    "ARTVİN",
    "AYDIN",
    "BALIKESİR",
    "BARTIN",
    "BATMAN",
    "BAYBURT",
    "BİLECİK",
    "BİNGÖL",
    "BİTLİS",
    "BOLU",
    "BURDUR",
    "BURSA",
    "ÇANAKKALE",
    "ÇANKIRI",
    "ÇORUM",
    "DENİZLİ",
    "DİYARBAKIR",
    "DÜZCE",
    "EDİRNE",
    "ELAZIĞ",
    "ERZİNCAN",
    "ERZURUM",
    "ESKİŞEHİR",
    "GAZİANTEP",
    "GİRESUN",
    "GÜMÜŞHANE",
    "HAKKARİ",
    "HATAY",
    "IĞDIR",
    "ISPARTA",
    "İSTANBUL",
    "İZMİR",
    "KAHRAMANMARAŞ",
    "KARABÜK",
    "KARAMAN",
    "KARS",
    "KASTAMONU",
    "KAYSERİ",
    "KIRIKKALE",
    "KIRKLARELİ",
    "KIRŞEHİR",
    "KİLİS",
    "KOCAELİ",
    "KONYA",
    "KÜTAHYA",
    "MALATYA",
    "MANİSA",
    "MARDİN",
    "MERSİN",
    "MUĞLA",
    "MUŞ",
    "NEVŞEHİR",
    "NİĞDE",
    "ORDU",
    "OSMANİYE",
    "RİZE",
    "SAKARYA",
    "SAMSUN",
    "SİİRT",
    "SİNOP",
    "SİVAS",
    "ŞANLIURFA",
    "ŞIRNAK",
    "TEKİRDAĞ",
    "TOKAT",
    "TRABZON",
    "TUNCELİ",
    "UŞAK",
    "VAN",
    "YALOVA",
    "YOZGAT",
    "ZONGULDAK"
]

# University types (same as lisans)
ONLISANS_UNIVERSITY_TYPES = [
    "Devlet",
    "Vakıf",
    "KKTC",
    "Yurt Dışı"
]

# Fee/Scholarship types (same as lisans)
ONLISANS_FEE_TYPES = [
    "Ücretsiz",
    "Ücretli",
    "İÖ-Ücretli",
    "Burslu",
    "%50 İndirimli",
    "%25 İndirimli",
    "AÖ-Ücretli",
    "UÖ-Ücretli"
]

# Education types (same as lisans)
ONLISANS_EDUCATION_TYPES = [
    "Örgün",
    "İkinci",
    "Açıköğretim",
    "Uzaktan"
]